{ lib, rustToolchain }:

{
  projectRootFile = "flake.nix";

  programs.nixfmt.enable = true;

  programs.rustfmt = {
    enable = true;
    package = rustToolchain;
    edition = "2024";
  };

  programs.yamlfmt.enable = true;

  programs.prettier.enable = true;
  programs.prettier.settings = {
    proseWrap = "always";
    printWidth = 76;
  };

  settings.formatter.prettier = {
    includes = lib.mkForce [ "*.md" ];
    excludes = [
      "docs/book/src/SUMMARY.md"

      # Generated by `nix run .#refresh-floe-docs`, and diffed byte for byte
      # against the generator by `floe-interface-<name>`. Reformatting them
      # here would make every one of those checks fail against a document
      # nobody wrote — and re-wrapping a table is not an improvement to a
      # file whose whole job is to be diffed.
      "docs/floes/*.md"
    ];
  };
}
