# Floe prose that describes something no longer here.
#
# A narrow check, and honest about it: it cannot judge whether a comment is
# good, only whether it names a thing that has been removed. Every entry below
# is a real removal, and each was found in the tree — `otel-collector`
# explained its whole design in terms of `requiresMany` for as long as that
# primitive had been gone, and twenty headers opened with a line count against
# a floe nobody can read.
#
# The rule it enforces, which the good headers already follow
# (`floes/cluster/lab-dns/default.nix`, `floes/cluster/openebs/default.nix`):
# a header is for someone using the floe *today*. What it installs, why it
# exists, and the decision they would otherwise reverse-engineer from the
# body. History belongs in `CHANGELOG.md`, which exists for exactly this.
#
# It reads `floes/` and the prose under `docs/`, because a removed primitive
# named in a guide misleads the same reader the same way. What it skips under
# `docs/`, and why — a document that is *about* what the tree used to be is
# the one place naming a removed thing is correct:
#
#   - `docs/rfcs/` — an RFC is a dated proposal. RFC 0001 names `requiresMany`
#     four times and must: three are its own original text, and the fourth is
#     the status block saying it is gone. Editing those would falsify the
#     record. What holds the RFCs honest instead is `rfc-refs`, which checks
#     that every `§N` citation resolves to a section that exists.
#   - `docs/prior-implementations.md` — the same, for the deleted tree. Its
#     subject is the parked floes, so naming them is the point.
#   - `docs/floes/` — generated by `nix/floe-interface.nix` from the floe
#     definitions, so a hit there is a hit in `floes/` already.
#   - the files in `namesTheOld` below, each for a stated reason. A glossary's
#     "what this used to be called" table is the one page where a removed name
#     belongs, and a check that forbade it would be demanding the docs be less
#     useful. Listed individually and deliberately, the way `renamed` works in
#     `floe-names.nix`.
#
# Which today leaves `floes/` and nothing else, since the book is not in this
# branch yet. The derivation records the file count it scanned rather than
# leaving "and docs/" to imply a coverage it does not have.
{ lib, pkgs }:

let
  # `pattern -> why it is dead`. The message is the check's whole value: a
  # grep hit with no explanation sends the reader to git log.
  dead = {
    "requiresMany" = "replaced by `requiresOptional` in lib/floe-core/floe.nix";
    "lines against" = "a line count against a deleted tree, wrong within one commit";
    "parked floe" = "the parked tree was deleted; see CHANGELOG.md";
    "parked tree" = "the parked tree was deleted; see CHANGELOG.md";
    "internalHostnames" = "the gateway fan-in was inverted; consumers render their own routes";
    "bootstrapManifests" = "now an `autoDeployManifests` input on the provisioner floe";
    "cluster.prerequisites" = "replaced by exactly-one-provider resolution";
    "ROUTE_REQUEST" = "the routing inversion removed it; see sigs.nix API_GATEWAY";
    ".exports" = "floes provide signatures; there is no exports channel";
  };

  # Pages whose *subject* is the renaming. Each earns its place by telling a
  # reader with older notes where a name went — which is the opposite of the
  # failure this check exists for, where prose describes a removed thing as
  # though it were live.
  namesTheOld = {
    "docs/book/src/reference/glossary.md" = "its last table is the old-name index";
    "docs/book/src/reference/floe-api.md" = "says why `requiresMany` was replaced";
    "docs/book/src/reference/helpers.md" = "maps every deleted helper to its replacement";
  };

  # Two roots, so a pattern that names a removed primitive fails wherever it
  # is written. `docs/` is copied minus the exclusions above.
  prose = pkgs.runCommand "floe-headers-prose" { } ''
    mkdir -p $out
    cp -r ${../../floes} $out/floes
    cp -r ${../../docs} $out/docs
    chmod -R u+w $out
    rm -rf $out/docs/rfcs $out/docs/floes $out/docs/prior-implementations.md
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (path: _: "rm -f $out/${path}") namesTheOld)}
  '';
in
{
  floe-headers = pkgs.runCommand "floe-headers-tests" { nativeBuildInputs = [ pkgs.gnugrep ]; } ''
    status=0
    cd ${prose}

    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (pattern: why: ''
        if hits=$(grep -rnF -- ${lib.escapeShellArg pattern} . 2>/dev/null); then
          echo "$hits" | sed 's/^/  /' >&2
          echo "    ^ mentions ${pattern}: ${why}" >&2
          echo "" >&2
          status=1
        fi
      '') dead
    )}

    if [ "$status" != 0 ]; then
      echo "A comment or a document describes something that is not in the" >&2
      echo "tree. Paths above are relative to the repo root." >&2
      echo "" >&2
      echo "A header is for someone using the floe today: what it installs," >&2
      echo "why it exists, and the decision they would otherwise work out by" >&2
      echo "reading the body. What the code used to be belongs in CHANGELOG.md." >&2
      echo "" >&2
      echo "docs/rfcs/ is exempt: an RFC is a dated proposal and may name what" >&2
      echo "it proposed. So are the pages in \`namesTheOld\` in this check," >&2
      echo "whose job is to say where an old name went. Adding one is a" >&2
      echo "deliberate act with a reason attached, not a way past the check." >&2
      exit 1
    fi
    echo "scanned $(find . -type f | wc -l) files under floes/ and docs/" > $out
  '';
}
